name: HarambeSquared
main: com.plotsquared.bukkit.BukkitMain
version: 1.0.0
load: STARTUP
description: >
             Easy, yet powerful Plot World generation and management.
authors: [Citymonstret, Empire92, MattBDev, Packet]
depend: [Lib]
database: false
commands:
  plots:
    description: PlotSquared PlotSquared command.
    aliases: [p,plot,plotme,ps,plotsquared,p2]